import React, { useState, useEffect } from 'react';
import moment from 'moment';
import { ExportExcel } from './ExportExcel';

const panoData = [
    {
        "coverage": "AKC",
        "bn_desc": "PREMIER",
        "link_to_rates": "AKC0000D",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 0,
        "vol_determin_ind": "",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "C1",
        "benefit_termination_reason_code": "",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "ACC000",
        "id": 1,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "AKC0000D",
        "specialWp1": "",
        "memberContributionCode": "",
        "dependentContributionCode": "VOLUNTARY",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "01/01/2018",
        "rateGuaranteeDate": "01/01/2020",
        "rateGuardSold": "RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "AKM",
        "bn_desc": "MEMBER ACCIDENT,VOLUNTARY",
        "link_to_rates": "AKM0000A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 0,
        "vol_determin_ind": "",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "M1",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "ACC000",
        "id": 2,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "AKM0000A",
        "specialWp1": "",
        "memberContributionCode": "VOLUNTARY",
        "dependentContributionCode": "",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "01/01/2018",
        "rateGuaranteeDate": "01/01/2020",
        "rateGuardSold": "RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "AKS",
        "bn_desc": "ADVANTAGE 2",
        "link_to_rates": "AKS0000D",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 0,
        "vol_determin_ind": "",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "S1",
        "benefit_termination_reason_code": "",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "ACC000",
        "id": 3,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "AKS0000D",
        "specialWp1": "",
        "memberContributionCode": "",
        "dependentContributionCode": "VOLUNTARY",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "01/01/2018",
        "rateGuaranteeDate": "01/01/2020",
        "rateGuardSold": "RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "CIM",
        "bn_desc": "PRE UAT CRITICAL ILLNESS TEST",
        "link_to_rates": "CIMF000A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "A489",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 20000,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "M1",
        "benefit_termination_reason_code": "",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "CIB000",
        "id": 4,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "CIMF000A",
        "specialWp1": "",
        "memberContributionCode": "CONTRIBUTORY",
        "dependentContributionCode": "",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "CVC",
        "bn_desc": "CI CHILD VOL,EOI,MULTI RATES,26/26",
        "link_to_rates": "VCCF012A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "5000",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 5000,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "H70",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "C1",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "CIB000",
        "id": 5,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "VCCF012A",
        "specialWp1": "",
        "memberContributionCode": "",
        "dependentContributionCode": "VOLUNTARY",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "CVM",
        "bn_desc": "CI MEMBER VOL,EOI,SMKR RTS",
        "link_to_rates": "VCMF002A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "12/01",
        "open_enroll_num_days": "31",
        "open_enroll_trans_date": "01/01",
        "lock_in_lock_out": "",
        "guar_issue_amt": "A491",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 20000,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "H70",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "M1",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "CIB000",
        "id": 6,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "VCMF002A",
        "specialWp1": "",
        "memberContributionCode": "VOLUNTARY",
        "dependentContributionCode": "",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "CVS",
        "bn_desc": "CI SPOUSE VOL,EOI,AGE 99,SMKR RATES",
        "link_to_rates": "VCSF014A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "A489",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 10000,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "H70",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "S1",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "CIB000",
        "id": 7,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "VCSF014A",
        "specialWp1": "",
        "memberContributionCode": "",
        "dependentContributionCode": "VOLUNTARY",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "RVC",
        "bn_desc": "CI RIDER CHILD VOL,MULTI RATES,26/26",
        "link_to_rates": "VRCF015A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 0,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "",
        "id": 8,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "VRCF015A",
        "specialWp1": "",
        "memberContributionCode": "",
        "dependentContributionCode": "VOLUNTARY",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "RVM",
        "bn_desc": "CI RIDER,MEMBER VOL,SMKR RATES",
        "link_to_rates": "VRMF002A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 0,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "",
        "id": 9,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "VRMF002A",
        "specialWp1": "",
        "memberContributionCode": "VOLUNTARY",
        "dependentContributionCode": "",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    },
    {
        "coverage": "RVS",
        "bn_desc": "CI RIDER,SPOUSE VOL,SMKR RATES,AGE 99",
        "link_to_rates": "VRSF011A",
        "eff_date": "20210101",
        "limit_date": "20991231",
        "pre_wp_txt": "1 OF THE MONTH FOLLOWING 30 DAYS             ",
        "fut_wp_txt": " 1 OF THE MONTH FOLLOWING 30 DAYS         ",
        "open_enroll_begin_date": "",
        "open_enroll_num_days": "0",
        "open_enroll_trans_date": "",
        "lock_in_lock_out": "",
        "guar_issue_amt": "",
        "guar_min_flat_cov": 0,
        "guar_max_cov": 0,
        "vol_determin_ind": "IMMEDIATE",
        "red_date": "/",
        "age_redetmination": "This should translate the Age Rate Change Code Field from Plan Dashboard",
        "age_cutback": "",
        "cl_uw_id": "",
        "product_type": "",
        "prov_num": "",
        "benefit_termination_reason_code": "D",
        "__typename": "PlanClassEXTInfo",
        "cfcoverage": "",
        "id": 10,
        "effectiveDate": "01/01/2021",
        "groupFactsId": "VRSF011A",
        "specialWp1": "",
        "memberContributionCode": "",
        "dependentContributionCode": "VOLUNTARY",
        "tiedToBenefit": "",
        "tiedToFor": "",
        "leaveLayOffCode": "1",
        "rateGuaranteePerEffDate": "",
        "rateGuaranteeDate": "",
        "rateGuardSold": "NO RATE GUARANTEE",
        "rateCapPc": "",
        "claimsOffice": "NRO CLAIMFACTS",
        "coverageProvisionNumber": 1
    }
]

const dataField = [
    {
        label: 'Coverage',
        key: "coverage",
    },
    {
        label: 'BN Desc',
        key: "bn_desc",
    },
    {
        label: 'Link Rates',
        key: "link_to_rates",
    },
    {
        label: 'Eff Date',
        key: "eff_date",
    },
    {
        label: 'Limit Date',
        key: "limit_date",
    },
    {
        label: 'Pre Wp Text',
        key: "pre_wp_txt",
    },
    {
        label: 'Group Facts ID',
        key: "groupFactsId",
    }
]
const MainExport = () => {
    const [exportKey, setExportKey] = useState(dataField);
    const [exportData, setExportData] = useState(panoData);

    useEffect(() => {
        const data = exportData.map(row => (
            { ...row, limit_date: moment(row.limit_date).format("YYYY-MM-DD") }
        ));
        setExportData(data);
    }, []);

    console.log('exportData', exportData);

    return (
        <div>
            <ExportExcel
                header={exportKey}
                data={exportData}
            />
        </div>
    )
}

export default MainExport;
